### ISSUE TITLE
Unable to connect to the remote server Exception 

### ISSUE THREAD

**Issue by edosssa** [brpeanut/Snippur#1]
@brpeanut If an attempt to connect to imgur is made when there is no active internet connection, the UploadImageAnnonymously method in Snippur.Core.Services throws an "unable to connect to the remote server exception". I think a check if there is an active connection should be added before running the method. Also appropriate feedback should be given to the user.

**Comment by bresheske** [comment]
@king-kay Thanks for the pull request.  Will close the issue since you took care of it.
