### ISSUE TITLE
Full screen screenshot feature

### ISSUE THREAD

**Issue by edosssa** [brpeanut/Snippur#3]
@brpeanut I was thinking if we could add a full screen screenshot feature to snippur. It would seem rather easy to implement because the project already supports grabbing subsets of the screen, so instead of letting the user drag the mouse, he/she just hits the take screenshot button  (to be implemented) and and a full screen picture is taken and saved. Although this seems to escape the bounds of a snippet tool but I do think it's a pretty nifty feature.

**Comment by bresheske** [comment]
Sounds good to me. Feel free to add it! You got this!

**Comment by edosssa** [comment]
Also, I would suggest that snippur once launched, remains on the tray and may be invoked by a key combination. So that there is no need to run the executable anytime a snipp is to be taken. Know any ways of levraging the system tray in wpf?

**Comment by bresheske** [comment]
I personally haven't used the tray at all, but I'm sure it can't be too complicated.  As a developer I would solve this my writing a small autohotkey script to launch the application via hotkey, but I know most users wouldn't know how to do that.

**Comment by edosssa** [comment]
@brpeanut  Had the same idea so i did a little research and wrote a keyboard hotkey class and added it to core services but then i'm not sure which approach to take from here. Should i launch the hook immediately after the app runs and just hide the window? What do you think? Also i tinkered with the wpf part, i gave it a nice style, removed the stock icons, changed the position of the docker that hosts the images(replaced with buttons), replaced the images with actual buttons but made their content the image so there can be a color variation when the mouse is over the button and also support tool tips.

**Comment by edosssa** [comment]
@brpeanut  I'm sorry for being so energetic. I just have really high expectations for this project because honestly speaking, i don't see a lot of attractive sniper tools out there that leverage new technologies like wpf.

**Comment by bresheske** [comment]
@king-kay 
No need to apologize man! If you think you can improve this tool in any way, I'll be open to the pull requests; feel free to go nuts.  :)

As far as the keyboard hook goes - There's probably a few different architectural approaches we can take.  I think we should add a configuration setting to the JSON configuration file (imgur.config) which sets the 'use hotkey' (or whatever the name would be) to true or false, then maybe another for 'which hotkey' to listen to.  Then would probably need to change the imgur.config name to something like settings.config as this feature has nothing to do with imgur.  

Now that we have some settings to read, we would need some process that runs in the background and listens to the keystrokes.  I think this should be a separate executable which is runnable outside of snippur (Maybe 'Snippur.Launcher' as the name).  This could be a simple console application that runs the first time snippur is launched, then stays alive forever and launches snippur when 'some event' happens.  This could also be a windows service that is set to startup on windows boot.  In order for a program to create a new service, the program needs elevated permissions, which is always a factor to consider.

On the design changes you mentioned - I'm not a huge fan of the current icons/style either.  It's something that was done quite a long time ago and is in need of update.  If we could make it something similar to either the windows 10 standard or the CSS bootstrap standard, that would be pretty great.

Thanks for the help!

**Comment by bresheske** [comment]
Also some other notes - The tool needs 2 more features.  
- Save to Clipboard: this has become more and more popular the last few years. Now most chat applications support control+V for passing images, and might not require any need for imgur.
- Drawing: after we've cropped a region, we should be able to make some drawings on it, like arrows or whatever.  I think since we're using WPF, this is probably very doable, but I haven't looked into it.

**Comment by king-kay** [comment]
Sounds like a plan! I'm not so experienced at the whole hotkey thing so i think i'll leave that to you. As for the designs i have made the following revisions to the xaml : Changed overall design, organised things a bit(added styles used by different elements), added better icon, and some other stuffs. It now looks a lot similar to the windows 10 game bar (purely coincidence) Here is what it looks like now :

![sample](https://cloud.githubusercontent.com/assets/20065279/18818281/a7c1d2ba-8375-11e6-983d-a7b374186050.PNG)
 
I't is basically a floating docker with buttons. So when we implement the hotkey, it simply brings up the docker and presto!

**Comment by edosssa** [comment]
Sounds like a plan! I'm not so experienced at the whole hotkey thing so i think i'll leave that to you. As for the designs i have made the following revisions to the xaml : 
- Changed overall design
- Organised things a bit(added styles used by different elements)
- Added better icons, and some other stuffs. 

Here are the mods i made to the xaml so far:

```
    <!--#region  Viual styles-->
    <Style x:Key="DockerButton" TargetType="{x:Type Button}">
        <Setter Property="FlowDirection" Value="LeftToRight"/>
        <Setter Property="BorderThickness" Value="0"></Setter>
        <Setter Property="Background" Value="Transparent"></Setter>
        <Setter Property="Cursor" Value="Hand"></Setter>
    </Style>

    <Style x:Key="DockerButtonImage" TargetType="{x:Type Image}">
        <Setter Property="FlowDirection" Value="LeftToRight"/>
        <Setter Property="Stretch" Value="None"></Setter>
        <Setter Property="Height" Value="50"></Setter>
        <Setter Property="Width" Value="50"></Setter>
    </Style>
    <!--#endregion-->

</Window.Resources>
<Grid x:Name="LayoutRoot">

    <!--#region Viual states and Animatiion-->
    <VisualStateManager.VisualStateGroups>
        <VisualStateGroup x:Name="VisualStateGroup" ei:ExtendedVisualStateManager.UseFluidLayout="True" >
            <VisualStateGroup.Transitions>
                <VisualTransition GeneratedDuration="0:0:0.6">
                    <VisualTransition.GeneratedEasingFunction>
                        <BackEase EasingMode="EaseInOut"/>
                    </VisualTransition.GeneratedEasingFunction>
                </VisualTransition>
            </VisualStateGroup.Transitions>
            <VisualState x:Name="Base"/>
            <VisualState x:Name="Menu">
                <Storyboard>
                    <ThicknessAnimationUsingKeyFrames Storyboard.TargetProperty="(FrameworkElement.Margin)" Storyboard.TargetName="grid">
                        <EasingThicknessKeyFrame KeyTime="0" Value="0"/>
                    </ThicknessAnimationUsingKeyFrames>
                </Storyboard>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
    <VisualStateManager.CustomVisualStateManager>
        <ei:ExtendedVisualStateManager/>
    </VisualStateManager.CustomVisualStateManager>
    <!--#endregion-->

    <Canvas x:Name="DrawingCanvas" Background="Black" Opacity="0.5"/>
    <Border Background="#2B2B2B" x:Name="grid" HorizontalAlignment="Center" VerticalAlignment="Top" Panel.ZIndex="1" Margin="0,-60,0,0"  MaxWidth="500">
        <StackPanel Orientation="Horizontal" HorizontalAlignment="Center">
                <Button Style="{DynamicResource DockerButton}" Click="TakeScreenSnip">
                    <Image  Source="Resources/icon_clipscreen.png" Style="{DynamicResource DockerButtonImage}" />
                </Button>
                <Button Style="{DynamicResource DockerButton}" Click="TakeScreenshotClick">
                    <Image Source="Resources/icon_screenshot.png" Style="{DynamicResource DockerButtonImage}"/>
                </Button>
                <Button Style="{DynamicResource DockerButton}" Click="SaveToFileClick">
                    <Image  Source="Resources/icon_saveclip_active.png" Style="{DynamicResource DockerButtonImage}"/>
                </Button>
                <Button Style="{DynamicResource DockerButton}">
                    <Image  Source="Resources/icon_resizeclip.png" Style="{DynamicResource DockerButtonImage}" />
                </Button>
            <Button Style="{DynamicResource DockerButton}">
                <Image  Source="Resources/icon_cancelclip_active.png" Style="{DynamicResource DockerButtonImage}" />
            </Button>
            <Button Style="{DynamicResource DockerButton}" Click="CloseClick">
                <Image  Source="Resources/icon_hidedocker.png" Style="{DynamicResource DockerButtonImage}" />
            </Button>
        </StackPanel>
    </Border>
</Grid>
```

</Window>

Here is what it looks like now :

![sample](https://cloud.githubusercontent.com/assets/20065279/18818281/a7c1d2ba-8375-11e6-983d-a7b374186050.PNG)

It's is basically a floating docker with buttons. So when we implement the hotkey, it simply brings up the docker and presto! I'm totally open to any design ideas you may have in mind to better improve the UI.

As for the features you mentioned, they all sound great and i look forward to us implementing them. Can i get your Email so we can communicate in a less 'githubby' fashion?
`

**Comment by bresheske** [comment]
Honestly the design looks great.  If you wanted to get that in, I'll approve it.

**Comment by edosssa** [comment]
Made a few chnages to the UI:

![sample](https://cloud.githubusercontent.com/assets/20065279/18846706/8a477228-8427-11e6-83f7-44b1fc7362ca.PNG)

Will make a pull request soon. Also, i discovered a problem with the screen capture, it flickers when you take a screenshot because you call this.Hide() and this.Show() before and after you take a screen capture. If you remove those, the saved snip will have a gray overlay.

**Comment by bresheske** [comment]
@king-kay 
I pushed a few updates - A few notes.
- Looks like you missed the CSProj file when adding the NetworkHelper.cs file, so the code didn't compile but 'Add Existing File' to my solution worked fine.
- The new UI didn't have an 'Upload to Imgur' button, so I added one using your Icon.

So I just quickly added some fixes.  Pretty minimal things.

Thanks

**Comment by bresheske** [comment]
Closing this issue as the feature for full screenshot has been implemented.
